package com.vistro.india.constants;


public interface SignupSqlConstants {
	
public static final String INSERT_INTO_SIGNUPTABLE="INSERT INTO user VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
public static final String SQL_SIGNIN_VALIDATION="SELECT COUNT(1) FROM user WHERE EmailID=? AND password=?";
//public static final String JOBSEARCH="SELECT skills,location,experience,result from student.jobsearch where skills='java' and location='bangalore' and experience=1";
//public static final String JOBSEARCH="select JobName, JobDescription from jobs where JobLocationID=(select LocationID from location where LocationName like '"+ LocationName+"') and SkillID = (select SkillID from skills where SkillName like '"+SkillName+"')";
//public static final String JOBSEARCH="select a.JobName, a.JobDescription, b.LocationName, c.SkillName from jobs a,location b,skills c where a.JobLocationID=b.LocationID and a.SkillID=c.SkillID and a.JobLocationID=(select LocationID from location where LocationName like 'bangalore') and a.SkillID = (select SkillID from skills where SkillName like 'java')";
public static final String SQL_PROFILE="SELECT EmailID,UserFirstName,UserLastName,Location,Dateofbirth,ContactNumber1,AddressLine1,Keyskills,Experience,ResumeSummary,Qualification,Specialisation,Yearofpassing,University,Companyname,Designation,Role,NoticePeriod FROM user where EmailID=? ";
//public static final String SQL_PROFILEUPDATE="UPDATE user SET  UserFirstName=?, UserLastName=?,CompanyEmailID=?, ProfileCompleteness=?,ResumeDocumentURL=?,PhotoURL=? ,IsCurrentlyWorking=?,IsResumeUploaded=?,IsResumeAutogenerated=?,IsEmailAlertEnabled=?, IsMobileAlertEnabled=?,LastLoggedIn=?,LastUpdated=?, Rating=?,LastAccessedIPAddress=?,NoOfActiveSessions=?,AddressLine1=?,AddressLine2=?,AddressLine3=?, Street=?,Location=?,StateID=?,ContactNumber1=?,ContactNumber2=?,CreatedDate=?, ModifiedDate=?,CreatedBy=?,Modifiedby=?,password=?,Dateofbirth=?, Gender=?,Experience=?,ResumeSummary=?,Keyskills=?,Qualification=?,Specialisation=?,Yearofpassing=?, University=?,Companyname=?,Designation=?,Role=?, NoticePeriod=? WHERE EmailID=? "; 
//public static final String SQL_PROFILECertification="SELECT CertificationName,Fromcertification,Tocertification FROM usercertifications WHERE USERID=2";
public static final String SQL_PROFILEQualification="select a.EmailID,c.CourseName,d.Specialisation,b.UniversityName,d.Yearofpassing from user a,university b,course c,userxuniversityxcourse d where a.UserID=d.UserID and d.CourseID=c.CourseID and d.universityID=b.universityID and a.UserID=(select UserID from user where EmailID=?)";
public static final String SQL_PROFILECertification2="SELECT  a.EmailID,b.CertificationName,b.Fromcertification,b.Tocertification FROM usercertifications b,user a WHERE a.userID=b.userID and a.UserID=(select UserID from user where EmailID=?)";
public static final String SQL_PROFILEUPDATE1="UPDATE user SET location=?,Dateofbirth=?,Keyskills=?,Experience=?,ContactNumber1=?,AddressLine1=?,ResumeSummary=?,ResumeDocumentURL=? WHERE EmailId=?";
//public static final String SQL_PROFILEUPDATEQUALIFICATION="INSERT INTO curse values(?,?,?,?)"
public static final String SQL_PROFILEQualification2="insert into userxuniversityxcourse (UniversityID,UserID,CourseID,Yearofpassing,specialisation) values ((select UniversityID from university where UniversityName=?),(select UserID from user where EmailID=?),(select CourseID from course where CourseName=?),?,?)";
public static final String JOBSEARCH="select j.jobid,j.jobname,j.jobdescription,l.locationname,jt.jobtypename from jobs j, location l, jobtype jt where j.joblocationid=l.locationid and j.jobtypeid=jt.jobtypeid and j.jobdescription like ";
		
}

