package com.vistro.india.bo;

public class User {
	private String UserID ;
	private String UserFirstName;
	private String UserLastName;
	private String EmailID;
	private String CompanyEmailID;
	private int ProfileCompleteness;
	private String ResumeDocumentURL;
	private String PhotoURL;
	private String IsCurrentlyWorking;
	private int	IsResumeUploaded;
	private int IsResumeAutogenerated;
	private int IsEmailAlertEnabled;
	private int IsMobileAlertEnabled;
	private String LastLoggedIn;
	private String LastUpdated;
	private int Rating;
	private String LastAccessedIPAddress;
	private int NoOfActiveSessions;
	private String AddressLine1;
	private String AddressLine2;
	private String AddressLine3;
	private String Street;
	private String Location;
	private String StateID;
	private String ContactNumber1;
	private String ContactNumber2;
	private String CreatedDate;
	private String ModifiedDate;
	private String CreatedBy;
	private String Modifiedby;
	private String password;
	private String Dateofbirth;
	private String Gender;
	private String Experience;
	private String ResumeSummary;
	
	
	

	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getUserID() {
		return UserID;
	}
	public void setUserID(String userID) {
		UserID = userID;
	}
	public String getUserFirstName() {
		return UserFirstName;
	}
	public void setUserFirstName(String userFirstName) {
		UserFirstName = userFirstName;
	}
	public String getUserLastName() {
		return UserLastName;
	}
	public void setUserLastName(String userLastName) {
		UserLastName = userLastName;
	}
	public String getEmailID() {
		return EmailID;
	}
	public void setEmailID(String emailID) {
		EmailID = emailID;
	}
	public String getCompanyEmailID() {
		return CompanyEmailID;
	}
	public void setCompanyEmailID(String companyEmailID) {
		CompanyEmailID = companyEmailID;
	}
	public int getProfileCompleteness() {
		return ProfileCompleteness;
	}
	public void setProfileCompleteness(int profileCompleteness) {
		ProfileCompleteness = profileCompleteness;
	}
	public String getResumeDocumentURL() {
		return ResumeDocumentURL;
	}
	public void setResumeDocumentURL(String resumeDocumentURL) {
		ResumeDocumentURL = resumeDocumentURL;
	}
	public String getPhotoURL() {
		return PhotoURL;
	}
	public void setPhotoURL(String photoURL) {
		PhotoURL = photoURL;
	}
	public String getIsCurrentlyWorking() {
		return IsCurrentlyWorking;
	}
	public void setIsCurrentlyWorking(String isCurrentlyWorking) {
		IsCurrentlyWorking = isCurrentlyWorking;
	}
	public int getIsResumeUploaded() {
		return IsResumeUploaded;
	}
	public void setIsResumeUploaded(int isResumeUploaded) {
		IsResumeUploaded = isResumeUploaded;
	}
	public int getIsResumeAutogenerated() {
		return IsResumeAutogenerated;
	}
	public void setIsResumeAutogenerated(int isResumeAutogenerated) {
		IsResumeAutogenerated = isResumeAutogenerated;
	}
	public int getIsEmailAlertEnabled() {
		return IsEmailAlertEnabled;
	}
	public void setIsEmailAlertEnabled(int isEmailAlertEnabled) {
		IsEmailAlertEnabled = isEmailAlertEnabled;
	}
	public int getIsMobileAlertEnabled() {
		return IsMobileAlertEnabled;
	}
	public void setIsMobileAlertEnabled(int isMobileAlertEnabled) {
		IsMobileAlertEnabled = isMobileAlertEnabled;
	}
	public String getLastLoggedIn() {
		return LastLoggedIn;
	}
	public void setLastLoggedIn(String lastLoggedIn) {
		LastLoggedIn = lastLoggedIn;
	}
	public String getLastUpdated() {
		return LastUpdated;
	}
	public void setLastUpdated(String lastUpdated) {
		LastUpdated = lastUpdated;
	}
	public int getRating() {
		return Rating;
	}
	public void setRating(int rating) {
		Rating = rating;
	}
	public String getLastAccessedIPAddress() {
		return LastAccessedIPAddress;
	}
	public void setLastAccessedIPAddress(String lastAccessedIPAddress) {
		LastAccessedIPAddress = lastAccessedIPAddress;
	}
	public int getNoOfActiveSessions() {
		return NoOfActiveSessions;
	}
	public void setNoOfActiveSessions(int noOfActiveSessions) {
		NoOfActiveSessions = noOfActiveSessions;
	}
	public String getAddressLine1() {
		return AddressLine1;
	}
	public void setAddressLine1(String addressLine1) {
		AddressLine1 = addressLine1;
	}
	public String getAddressLine2() {
		return AddressLine2;
	}
	public void setAddressLine2(String addressLine2) {
		AddressLine2 = addressLine2;
	}
	public String getAddressLine3() {
		return AddressLine3;
	}
	public void setAddressLine3(String addressLine3) {
		AddressLine3 = addressLine3;
	}
	public String getStreet() {
		return Street;
	}
	public void setStreet(String street) {
		Street = street;
	}
	public String getLocation() {
		return Location;
	}
	public void setLocation(String location) {
		Location = location;
	}
	public String getStateID() {
		return StateID;
	}
	public void setStateID(String stateID) {
		StateID = stateID;
	}
	public String getContactNumber1() {
		return ContactNumber1;
	}
	public void setContactNumber1(String contactNumber1) {
		ContactNumber1 = contactNumber1;
	}
	public String getContactNumber2() {
		return ContactNumber2;
	}
	public void setContactNumber2(String contactNumber2) {
		ContactNumber2 = contactNumber2;
	}
	public String getCreatedDate() {
		return CreatedDate;
	}
	public void setCreatedDate(String createdDate) {
		CreatedDate = createdDate;
	}
	public String getModifiedDate() {
		return ModifiedDate;
	}
	public void setModifiedDate(String modifiedDate) {
		ModifiedDate = modifiedDate;
	}
	public String getCreatedBy() {
		return CreatedBy;
	}
	public void setCreatedBy(String createdBy) {
		CreatedBy = createdBy;
	}
	public String getModifiedby() {
		return Modifiedby;
	}
	public void setModifiedby(String modifiedby) {
		Modifiedby = modifiedby;
	}
	
	public String getDateofbirth() {
		return Dateofbirth;
	}
	public void setDateofbirth(String dateofbirth) {
		Dateofbirth = dateofbirth;
	}
	public String getGender() {
		return Gender;
	}
	public void setGender(String gender) {
		Gender = gender;
	}
	public String getExperience() {
		return Experience;
	}
	public void setExperience(String experience) {
		Experience = experience;
	}
	public String getResumeSummary() {
		return ResumeSummary;
	}
	public void setResumeSummary(String resumeSummary) {
		ResumeSummary = resumeSummary;
	}


}